# site settings
title: Pedro Cruz
subtitle:
email: apedrocruz@tecnico.ulisboa.pt
description: Student at Instituto Superior Técnico, Lisbon.<br /> MSc in Engineering Systems and Computer Engineering with focus on cyber-security. <br /> Traveller. Curious. Ambitious. Open-minded.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
city: Lisbon
country: Portugal

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://www.github.com/pedrocrvz
linkedin_url: https://www.linkedin.com/in/pedrocrvz
twitter_url: https://twitter.com/pedrocrvz

# build settings
markdown: kramdown

sass:
  style: compressed
